apiVersion: v1
kind: Service
metadata:
  name: {{ include "csgo.fullname" . }}
  labels:
    {{- include "csgo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.game_port }}
      targetPort: {{ .Values.rcon_port }}
      nodePort: {{ .Values.rcon_port }}
      protocol: TCP
      name: rcon
    - port: {{ .Values.game_port }}
      targetPort: {{ .Values.game_port }}
      nodePort: {{ .Values.game_port }}
      protocol: UDP
      name: game
    - port: {{ .Values.tv_port }}
      targetPort: {{ .Values.tv_port }}
      nodePort: {{ .Values.tv_port }}
      protocol: UDP
      name: tv
    - port: {{ .Values.client_port }}
      targetPort: {{ .Values.client_port }}
      nodePort: {{ .Values.client_port }}
      protocol: UDP
      name: client
  selector:
    {{- include "csgo.selectorLabels" . | nindent 4 }}
